plugins {
    id 'org.springframework.boot' version '4.1.0' 
    id 'io.spring.dependency-management' version '1.1.7'
    id 'java'
    id 'eclipse-wtp'
}

group = 'com.dyinfotech'
version = '0.0.1-SNAPSHOT'
description = 'annual-leave-backend'

java {
	// disable toolchain because of avoiding error
	// Class org.gradle.jvm.toolchain.JvmVendorSpec does not have member field 'org.gradle.jvm.toolchain.JvmVendorSpec IBM_SEMERU'
    //toolchain {
    //    languageVersion = JavaLanguageVersion.of(21)
    //}
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

eclipse {
    wtp {
        facet {
            facet name: 'java', version: '21'
        }
    }
    
    jdt {
        file {
            withProperties { properties ->
                properties.setProperty('org.eclipse.jdt.core.compiler.codegen.methodParameters', 'generate')
            }
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-security'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework.boot:spring-boot-starter-webmvc'
    // WebClient (alternative RestClient because of spring boot 4.x.x to 3.0.12)
    implementation('org.springframework.boot:spring-boot-starter-webflux') {
    	// don't need netty starter engine (high performance but heavy library)
        exclude group: 'org.springframework.boot', module: 'spring-boot-starter-reactor-netty'
    }
    implementation 'org.springframework.boot:spring-boot-starter-mail'
    implementation 'org.springframework.boot:spring-boot-starter-cache'
    // Jackson Databind (ObjectMapper)
    implementation 'org.springframework.boot:spring-boot-starter-json'
    developmentOnly 'org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.2'
    
    compileOnly 'org.projectlombok:lombok'
    runtimeOnly 'com.mysql:mysql-connector-j'
    annotationProcessor 'org.projectlombok:lombok'
    testImplementation 'org.springframework.boot:spring-boot-starter-data-jpa-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-security-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-validation-test'
    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
    testCompileOnly 'org.projectlombok:lombok'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testAnnotationProcessor 'org.projectlombok:lombok'

    implementation 'io.jsonwebtoken:jjwt-api:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-impl:0.12.6'
    runtimeOnly 'io.jsonwebtoken:jjwt-jackson:0.12.6'
    
    // Firebase Admin SDK
    implementation('com.google.firebase:firebase-admin:9.10.0') {
	    // don't need Firestore(NoSQL DB) feature
	    exclude group: 'com.google.cloud', module: 'google-cloud-firestore'
    	exclude group: 'com.google.api.grpc', module: 'proto-google-cloud-firestore-v1'
	    
	    // don't need Cloud Storage(File Upload) feature
	    exclude group: 'com.google.cloud', module: 'google-cloud-storage'
	    
	    // don't need communication specifications and duplicate transfer libraries (gRPCs)
	    // TODO: need to re-examine if really don't use it when subscribing to and pushing a topic
	    exclude group: 'io.grpc'
	    exclude group: 'com.google.api.grpc'
	    
	    // don't need mock-server
	    exclude group: 'org.mock-server', module: 'mockserver-junit-rule-no-dependencies'
	    
	    // don't need netty (WebFlux also do)
	    exclude group: 'io.netty'
	}
    
    // Caffeine Cache
    implementation 'com.github.ben-manes.caffeine:caffeine'
    
    // sql log parameter setting
	implementation 'com.github.gavlyukovskiy:p6spy-spring-boot-starter:2.0.1'
}

tasks.withType(JavaCompile) {
    options.release = 21
    options.compilerArgs.add("-parameters")
}

tasks.named('test') {
    useJUnitPlatform()
    systemProperty 'file.encoding', 'UTF-8'
}

bootJar {
    archiveFileName = 'annual-leave-backend.jar'
}
