spring:
  application:
    name: annual-leave-backend

  config:
    import: "optional:file:.env[.properties]" # .env file load

  threads:
    virtual:
      enabled: true

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
   show-sql: false         # ⚠️ 파일 로그에도 기록하기 위해 false로 두고 아래 logging에서 제어합니다.
   properties:
    hibernate:
     format_sql: true      # SQL 쿼리를 한 줄이 아니라 개행/들여쓰기로 예쁘게 포맷팅
     highlight_sql: true   # 콘솔창에서 SQL 키워드에 색상을 입혀 가독성 향상

  mail:
    host: smtp.cafe24.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
     mail:
       smtp:
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          starttls:
            enable: true
            required: true

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000   # 1시간

openapi:
  service-key: ${SERVICE_KEY}

fcm:
  certification: classpath:firebase-service-account.json

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:*,http://127.0.0.1:*}

logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

  file:
   name: logs/local-app.log

  # 🔄 파일 로테이션 설정 (서버 용량 방어를 위해 무조건 넣는 것을 추천합니다)
  logback:
    rollingpolicy:
      file-name-pattern: "logs/local-app.%d{yyyy-MM-dd}.%i.log"
      max-file-size: 10MB
