spring:
  application:
    name: annual-leave-backend

  config:
    import: "optional:file:.env[.properties]" # .env file load

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
   show-sql: false         # ⚠️ 파일 로그에도 기록하기 위해 false로 두고 아래 logging에서 제어합니다.
   properties:
    hibernate:
     format_sql: false     # 운영시 포맷팅 불필요. 용량 차지 저하.
     highlight_sql: false  # sql 키워드 색상은 콘솔상 필요조건. 파일에선 불필요한 낭비.

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
     mail:
       smtp:
         auth: true
         connectiontimeout: 5000
         timeout: 5000
         writetimeout: 5000 
         starttls:
           enable: true
           required: true
           ssl:
             protocols: TLSv1 TLSv1.1 TLSv1.2 TLSv1.3
    
jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_TIMEOUT:3600000}   # 1시간

openapi:
  service-key: ${SERVICE_KEY}

fcm:
  certification: ${FIREBASE_CREDENTIAL_PATH:classpath:firebase-service-account.json}

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:*,http://127.0.0.1:*,https://app.dyinfotech.com}

logging:
  level:
    root: info
    org.springframework.boot.autoconfigure: error  # Condition Evaluation Report log  disable
    org.hibernate.SQL: info                        # disable sql log (use p6spy)
    org.hibernate.orm.jdbc.bind: info              # disable sql parameter log (use p6spy)

    com.dyinfotech.annualleavebackend: info       # @Slf4j log level
  
  pattern:
    console: "%clr(%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %replace(%m | clientIp=%X{clientIp}){' \\| clientIp=$',''}%n"
    file: "%d{yyyy-MM-dd'T'HH:mm:ss.SSSXXX} %5p ${PID:- } --- [%15.15t] %-40.40logger{39} : %replace(%m | clientIp=%X{clientIp}){' \\| clientIp=$',''}%n"

  file:
   name: logs/local-app.log

  # 파일 로테이션 설정 (서버 용량 방어)
  logback:
    rollingpolicy:
      file-name-pattern: "logs/local-app.%d{yyyy-MM-dd}.%i.log.gz"
      max-file-size: 1MB
      max-history: 30
      total-size-cap: 35MB
      clean-history-on-start: true

# p6spy
decorator:
  datasource:
    p6spy:
      enable-logging: true