appender=com.p6spy.engine.spy.appender.StdoutLogger
logMessageFormat=com.p6spy.engine.spy.appender.CustomLineFormat
dateformat=yyyy-MM-dd'T'HH:mm:ss.SSSXXX
customLogMessageFormat=%(currentTime) [P6Spy] Connection: %(connectionId) | Time: %(executionTime)ms | %(sql)