-- =====================================================================
-- Durable notification outbox for develop_v2.0
-- Apply once to existing v2 Oracle databases before deploying code that
-- maps NotificationOutbox. Fresh installs use sql/schema.sql.
-- =====================================================================

WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM user_tables
     WHERE table_name = 'NOTIFICATION_OUTBOX';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE notification_outbox (
                outbox_id        NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                approver_ids     CLOB NOT NULL,
                title            VARCHAR2(200 CHAR) NOT NULL,
                body             VARCHAR2(1000 CHAR) NOT NULL,
                status           VARCHAR2(20 CHAR) DEFAULT 'PENDING' NOT NULL,
                attempt_count    NUMBER(10) DEFAULT 0 NOT NULL,
                next_attempt_at  TIMESTAMP(6) NOT NULL,
                claimed_at       TIMESTAMP(6),
                sent_at          TIMESTAMP(6),
                last_error       VARCHAR2(1000 CHAR),
                created_at       TIMESTAMP(6) NOT NULL,
                CONSTRAINT pk_notification_outbox PRIMARY KEY (outbox_id),
                CONSTRAINT ck_notification_outbox_status
                    CHECK (status IN ('PENDING', 'PROCESSING', 'SENT', 'DEAD')),
                CONSTRAINT ck_notification_outbox_attempt
                    CHECK (attempt_count >= 0)
            )
        ]';
    END IF;
END;
/

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*)
      INTO v_count
      FROM user_indexes
     WHERE index_name = 'IX_NOTIFICATION_OUTBOX_READY';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE INDEX ix_notification_outbox_ready '
            || 'ON notification_outbox(status, next_attempt_at, outbox_id)';
    END IF;
END;
/
