-- Add password reset token storage to an already-normalized develop_v2.0 Oracle schema.
WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count
      FROM user_tables
     WHERE table_name = 'PASSWORD_RESET_TOKEN';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE q'[
            CREATE TABLE password_reset_token (
                token_id     NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
                employee_id  NUMBER(19) NOT NULL,
                token_hash   VARCHAR2(64 CHAR) NOT NULL,
                expires_at   TIMESTAMP(6) NOT NULL,
                consumed_at  TIMESTAMP(6),
                created_at   TIMESTAMP(6) NOT NULL,
                CONSTRAINT pk_password_reset_token PRIMARY KEY (token_id),
                CONSTRAINT uk_password_reset_token_hash UNIQUE (token_hash),
                CONSTRAINT fk_password_reset_employee
                    FOREIGN KEY (employee_id) REFERENCES employee(employee_id)
            )
        ]';
    END IF;

    SELECT COUNT(*) INTO v_count
      FROM user_indexes
     WHERE index_name = 'IX_PASSWORD_RESET_EMPLOYEE';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE
            'CREATE INDEX ix_password_reset_employee ON password_reset_token(employee_id)';
    END IF;
END;
/

COMMIT;
