-- =====================================================================
-- annual-leave develop_v2.0
-- Oracle 21c XE canonical fresh-install schema
--
-- Fresh database: use this file.
-- Existing develop_v1.0 database: use migration_v2_0_oracle.sql instead.
-- Oracle DDL performs implicit commits; back up an existing database first.
-- =====================================================================

WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

CREATE TABLE department (
    department_id   NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    department_name VARCHAR2(50 CHAR) NOT NULL,
    enabled         NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT pk_department PRIMARY KEY (department_id),
    CONSTRAINT uk_department_name UNIQUE (department_name),
    CONSTRAINT ck_department_enabled CHECK (enabled IN (0, 1))
);

CREATE TABLE team (
    team_id             NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    team_name           VARCHAR2(30 CHAR) NOT NULL,
    department_id       NUMBER(19) NOT NULL,
    enabled             NUMBER(1) DEFAULT 1 NOT NULL,
    create_request_key  VARCHAR2(128 CHAR),
    create_request_hash VARCHAR2(64 CHAR),
    CONSTRAINT pk_team PRIMARY KEY (team_id),
    CONSTRAINT uk_team_name UNIQUE (team_name),
    CONSTRAINT uk_team_create_request UNIQUE (create_request_key),
    CONSTRAINT ck_team_enabled CHECK (enabled IN (0, 1)),
    CONSTRAINT ck_team_create_request_pair CHECK (
        (create_request_key IS NULL AND create_request_hash IS NULL)
        OR
        (create_request_key IS NOT NULL AND create_request_hash IS NOT NULL)
    ),
    CONSTRAINT fk_team_department
        FOREIGN KEY (department_id) REFERENCES department(department_id)
);

CREATE TABLE employee (
    employee_id           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    employee_number       VARCHAR2(20 CHAR) NOT NULL,
    password              VARCHAR2(255 CHAR),
    access_count          NUMBER(10) DEFAULT 0 NOT NULL,
    accessed_ip           VARCHAR2(45 CHAR),
    accessed_at           TIMESTAMP(6),
    name                  VARCHAR2(50 CHAR) NOT NULL,
    department_id         NUMBER(19) NOT NULL,
    team_id               NUMBER(19) NOT NULL,
    position              VARCHAR2(50 CHAR),
    email                 VARCHAR2(100 CHAR),
    curr_year             VARCHAR2(4 CHAR) NOT NULL,
    curr_total_leave_days BINARY_FLOAT DEFAULT 0 NOT NULL,
    prev_year             VARCHAR2(4 CHAR),
    prev_total_leave_days BINARY_FLOAT,
    hire_date             DATE NOT NULL,
    fire_date             DATE,
    approver_id           NUMBER(19) NOT NULL,
    created_at            TIMESTAMP(6) NOT NULL,
    created_ip            VARCHAR2(45 CHAR) NOT NULL,
    updated_at            TIMESTAMP(6) NOT NULL,
    updated_ip            VARCHAR2(45 CHAR),
    CONSTRAINT pk_employee PRIMARY KEY (employee_id),
    CONSTRAINT uk_employee_number UNIQUE (employee_number),
    CONSTRAINT fk_employee_department
        FOREIGN KEY (department_id) REFERENCES department(department_id),
    CONSTRAINT fk_employee_team
        FOREIGN KEY (team_id) REFERENCES team(team_id),
    CONSTRAINT fk_employee_approver
        FOREIGN KEY (approver_id) REFERENCES employee(employee_id)
);

CREATE TABLE team_manager (
    team_id            NUMBER(19) NOT NULL,
    project_manager_id NUMBER(19) NOT NULL,
    parent_team_id     NUMBER(19) NOT NULL,
    CONSTRAINT pk_team_manager PRIMARY KEY (team_id, project_manager_id),
    CONSTRAINT fk_team_manager_team
        FOREIGN KEY (team_id) REFERENCES team(team_id),
    CONSTRAINT fk_team_manager_project_manager
        FOREIGN KEY (project_manager_id) REFERENCES employee(employee_id),
    CONSTRAINT fk_team_manager_parent_team
        FOREIGN KEY (parent_team_id) REFERENCES team(team_id)
);

CREATE TABLE leave_request (
    leave_request_id      NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    employee_id           NUMBER(19) NOT NULL,
    leave_type            VARCHAR2(50 CHAR) NOT NULL,
    start_date            DATE NOT NULL,
    end_date              DATE NOT NULL,
    use_days              BINARY_FLOAT NOT NULL,
    prev_total_leave_days BINARY_FLOAT NOT NULL,
    curr_total_leave_days BINARY_FLOAT NOT NULL,
    leave_reason          VARCHAR2(200 CHAR),
    status                VARCHAR2(10 CHAR) DEFAULT 'PENDING' NOT NULL,
    manager_id            NUMBER(19),
    managed_at            TIMESTAMP(6),
    managed_ip            VARCHAR2(45 CHAR),
    reject_reason         VARCHAR2(200 CHAR),
    created_at            TIMESTAMP(6) NOT NULL,
    created_ip            VARCHAR2(45 CHAR) NOT NULL,
    CONSTRAINT pk_leave_request PRIMARY KEY (leave_request_id),
    CONSTRAINT fk_leave_request_employee
        FOREIGN KEY (employee_id) REFERENCES employee(employee_id),
    CONSTRAINT fk_leave_request_manager
        FOREIGN KEY (manager_id) REFERENCES employee(employee_id),
    CONSTRAINT ck_leave_request_status CHECK (
        status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')
    )
);

CREATE TABLE basis_data (
    year   VARCHAR2(4 CHAR) NOT NULL,
    seq    NUMBER(19) NOT NULL,
    type   VARCHAR2(2 CHAR),
    data   VARCHAR2(255 CHAR),
    remark VARCHAR2(200 CHAR),
    CONSTRAINT pk_basis_data PRIMARY KEY (year, seq)
);

CREATE TABLE leave_adjustment (
    employee_id NUMBER(19) NOT NULL,
    year        VARCHAR2(4 CHAR) NOT NULL,
    sign        VARCHAR2(5 CHAR),
    leave_days  BINARY_FLOAT NOT NULL,
    reason      VARCHAR2(200 CHAR),
    created_at  TIMESTAMP(6) NOT NULL,
    created_ip  VARCHAR2(45 CHAR) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL,
    updated_ip  VARCHAR2(45 CHAR),
    CONSTRAINT pk_leave_adjustment PRIMARY KEY (employee_id, year, created_at),
    CONSTRAINT fk_leave_adjustment_employee
        FOREIGN KEY (employee_id) REFERENCES employee(employee_id)
);

CREATE TABLE holiday (
    holiday_date DATE NOT NULL,
    name         VARCHAR2(50 CHAR),
    CONSTRAINT pk_holiday PRIMARY KEY (holiday_date)
);

CREATE TABLE fcm_token (
    token_id    NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    employee_id NUMBER(19),
    fcm_token   VARCHAR2(255 CHAR) NOT NULL,
    device_os   VARCHAR2(255 CHAR),
    updated_at  TIMESTAMP(6) NOT NULL,
    updated_ip  VARCHAR2(45 CHAR),
    CONSTRAINT pk_fcm_token PRIMARY KEY (token_id),
    CONSTRAINT uk_fcm_token UNIQUE (fcm_token),
    CONSTRAINT fk_fcm_token_employee
        FOREIGN KEY (employee_id) REFERENCES employee(employee_id)
);

CREATE TABLE password_reset_token (
    token_id     NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    employee_id  NUMBER(19) NOT NULL,
    token_hash   VARCHAR2(64 CHAR) NOT NULL,
    expires_at   TIMESTAMP(6) NOT NULL,
    consumed_at  TIMESTAMP(6),
    created_at   TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_password_reset_token PRIMARY KEY (token_id),
    CONSTRAINT uk_password_reset_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_password_reset_employee
        FOREIGN KEY (employee_id) REFERENCES employee(employee_id)
);

CREATE INDEX ix_employee_team ON employee(team_id);
CREATE INDEX ix_employee_department ON employee(department_id);
CREATE INDEX ix_team_department ON team(department_id);
CREATE INDEX ix_leave_request_employee ON leave_request(employee_id);
CREATE INDEX ix_leave_request_status_dates
    ON leave_request(status, start_date, end_date);
CREATE INDEX ix_team_manager_parent ON team_manager(parent_team_id);
CREATE INDEX ix_team_manager_project_manager ON team_manager(project_manager_id);
CREATE INDEX ix_password_reset_employee ON password_reset_token(employee_id);
