-- =====================================================================
-- annual-leave develop_v2.0
-- Oracle 21c XE canonical fresh-install schema
--
-- Fresh database: use this file after DBA creates COMMON_DATA / COMMON_INDEX.
-- This fresh-install schema includes AUTH_REFRESH_SESSION.
-- Existing develop_v1.0 database: use migration_v2_0_oracle.sql only.
-- The v1 -> v2 application migration leaves an already-existing shared
-- AUTH_REFRESH_SESSION untouched; it only migrates annual-leave application objects.
-- Oracle DDL performs implicit commits; back up an existing database first.
-- =====================================================================

WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

CREATE TABLE department (
    department_id   NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    department_name VARCHAR2(50 CHAR) NOT NULL,
    enabled         NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT pk_department PRIMARY KEY (department_id),
    CONSTRAINT uk_department_name UNIQUE (department_name),
    CONSTRAINT ck_department_enabled CHECK (enabled IN (0, 1))
);

CREATE TABLE team (
    team_id             NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    team_name           VARCHAR2(30 CHAR) NOT NULL,
    department_id       NUMBER(19) NOT NULL,
    enabled             NUMBER(1) DEFAULT 1 NOT NULL,
    create_request_key  VARCHAR2(128 CHAR),
    create_request_hash VARCHAR2(64 CHAR),
    CONSTRAINT pk_team PRIMARY KEY (team_id),
    CONSTRAINT uk_team_name UNIQUE (team_name),
    CONSTRAINT uk_team_create_request UNIQUE (create_request_key),
    CONSTRAINT ck_team_enabled CHECK (enabled IN (0, 1)),
    CONSTRAINT ck_team_create_request_pair CHECK (
        (create_request_key IS NULL AND create_request_hash IS NULL)
        OR
        (create_request_key IS NOT NULL AND create_request_hash IS NOT NULL)
    ),
    CONSTRAINT fk_team_department
        FOREIGN KEY (department_id) REFERENCES department(department_id)
);

CREATE TABLE employee (
    employee_id           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    employee_number       VARCHAR2(20 CHAR) NOT NULL,
    password              VARCHAR2(255 CHAR),
    access_count          NUMBER(10) DEFAULT 0 NOT NULL,
    accessed_ip           VARCHAR2(45 CHAR),
    accessed_at           TIMESTAMP(6),
    name                  VARCHAR2(50 CHAR) NOT NULL,
    department_id         NUMBER(19) NOT NULL,
    team_id               NUMBER(19) NOT NULL,
    position              VARCHAR2(50 CHAR),
    email                 VARCHAR2(100 CHAR),
    curr_year             VARCHAR2(4 CHAR) NOT NULL,
    curr_total_leave_days BINARY_FLOAT DEFAULT 0 NOT NULL,
    prev_year             VARCHAR2(4 CHAR),
    prev_total_leave_days BINARY_FLOAT,
    hire_date             DATE NOT NULL,
    fire_date             DATE,
    approver_id           NUMBER(19) NOT NULL,
    created_at            TIMESTAMP(6) NOT NULL,
    created_ip            VARCHAR2(45 CHAR) NOT NULL,
    updated_at            TIMESTAMP(6) NOT NULL,
    updated_ip            VARCHAR2(45 CHAR),
    CONSTRAINT pk_employee PRIMARY KEY (employee_id),
    CONSTRAINT uk_employee_number UNIQUE (employee_number),
    CONSTRAINT fk_employee_department
        FOREIGN KEY (department_id) REFERENCES department(department_id),
    CONSTRAINT fk_employee_team
        FOREIGN KEY (team_id) REFERENCES team(team_id),
    CONSTRAINT fk_employee_approver
        FOREIGN KEY (approver_id) REFERENCES employee(employee_id)
);

-- =====================================================================
-- 공통 SSO Refresh Token Rotation session
--
-- 연차/자산관리가 같은 refresh family/session row를 사용한다.
-- COMMON_DATA / COMMON_INDEX는 sql/dba_prepare_common_auth_tablespace.sql로 DBA가 먼저 준비한다.
-- =====================================================================
CREATE TABLE auth_refresh_session (
    session_id                VARCHAR2(36)      NOT NULL,
    employee_id               NUMBER(19)        NOT NULL,
    token_hash                VARCHAR2(64)      NOT NULL,
    previous_token_hash       VARCHAR2(64),
    previous_valid_until      TIMESTAMP(6),
    created_at                TIMESTAMP(6)      NOT NULL,
    last_rotated_at           TIMESTAMP(6)      NOT NULL,
    idle_expires_at           TIMESTAMP(6)      NOT NULL,
    absolute_expires_at       TIMESTAMP(6)      NOT NULL,
    revoked_at                TIMESTAMP(6),
    revoked_reason            VARCHAR2(40),
    rotation_count            NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT pk_auth_refresh_session
        PRIMARY KEY (session_id) USING INDEX TABLESPACE COMMON_INDEX,
    CONSTRAINT fk_ars_employee
        FOREIGN KEY (employee_id) REFERENCES employee(employee_id),
    CONSTRAINT ck_ars_rotation_count CHECK (rotation_count >= 0),
    CONSTRAINT ck_ars_expiry_order CHECK (idle_expires_at <= absolute_expires_at)
)
TABLESPACE COMMON_DATA;

CREATE INDEX ix_ars_employee
    ON auth_refresh_session(employee_id)
    TABLESPACE COMMON_INDEX;

CREATE INDEX ix_ars_expiry
    ON auth_refresh_session(absolute_expires_at, idle_expires_at)
    TABLESPACE COMMON_INDEX;

COMMENT ON TABLE auth_refresh_session
    IS '연차/자산관리 공통 Web SSO Refresh Token Rotation 세션. 원문 token은 저장하지 않는다.';

CREATE TABLE team_manager (
    team_id            NUMBER(19) NOT NULL,
    project_manager_id NUMBER(19) NOT NULL,
    parent_team_id     NUMBER(19) NOT NULL,
    CONSTRAINT pk_team_manager PRIMARY KEY (team_id, project_manager_id),
    CONSTRAINT fk_team_manager_team
        FOREIGN KEY (team_id) REFERENCES team(team_id),
    CONSTRAINT fk_team_manager_project_manager
        FOREIGN KEY (project_manager_id) REFERENCES employee(employee_id),
    CONSTRAINT fk_team_manager_parent_team
        FOREIGN KEY (parent_team_id) REFERENCES team(team_id)
);

-- =====================================================================
-- DB-level guard: PM 퇴사일 직접 UPDATE로 결재 공백이 생기는 것을 차단한다.
--
-- Row trigger에서 EMPLOYEE를 다시 조회하면 ORA-04091(mutating table)이 발생할 수
-- 있으므로 compound trigger의 AFTER STATEMENT 단계에서 최종 상태를 검증한다.
-- 한 UPDATE문에서 여러 PM의 FIRE_DATE를 동시에 바꾸는 경우도 최종 상태 기준으로
-- 함께 검증된다.
-- =====================================================================
CREATE OR REPLACE TRIGGER trg_employee_pm_fire_date_guard
FOR UPDATE OF fire_date ON employee
COMPOUND TRIGGER

    TYPE t_employee_id_list IS TABLE OF NUMBER(19) INDEX BY PLS_INTEGER;
    g_employee_ids t_employee_id_list;
    g_employee_count PLS_INTEGER := 0;

    AFTER EACH ROW IS
    BEGIN
        -- 퇴사일 제거(NULL)는 재활성화 방향이므로 차단 대상이 아니다.
        IF :NEW.fire_date IS NOT NULL
           AND (:OLD.fire_date IS NULL OR :OLD.fire_date <> :NEW.fire_date) THEN
            g_employee_count := g_employee_count + 1;
            g_employee_ids(g_employee_count) := :NEW.employee_id;
        END IF;
    END AFTER EACH ROW;

    AFTER STATEMENT IS
        v_fire_date      DATE;
        v_inactive_from  DATE;
        v_check_date     DATE;
        v_gap_team_count NUMBER;
    BEGIN
        FOR i IN 1 .. g_employee_count LOOP
            SELECT fire_date
              INTO v_fire_date
              FROM employee
             WHERE employee_id = g_employee_ids(i);

            IF v_fire_date IS NULL THEN
                CONTINUE;
            END IF;

            -- LocalDate.MAX(9999-12-31)는 +1 시 Oracle DATE 범위를 벗어날 수 있다.
            IF v_fire_date >= DATE '9999-12-31' THEN
                v_inactive_from := v_fire_date;
            ELSE
                v_inactive_from := v_fire_date + 1;
            END IF;

            -- 과거 일자로 소급 퇴사 처리하더라도 현재 조직에 결재 공백이 생기면 막는다.
            v_check_date := GREATEST(v_inactive_from, TRUNC(SYSDATE));

            SELECT COUNT(DISTINCT tm.team_id)
              INTO v_gap_team_count
              FROM team_manager tm
             WHERE tm.project_manager_id = g_employee_ids(i)
               AND (
                    EXISTS (
                        SELECT 1
                          FROM employee dependent_employee
                         WHERE dependent_employee.team_id = tm.team_id
                           AND dependent_employee.employee_id <> g_employee_ids(i)
                           AND dependent_employee.hire_date <= v_check_date
                           AND (
                                dependent_employee.fire_date IS NULL
                                OR dependent_employee.fire_date >= v_check_date
                           )
                    )
                    OR EXISTS (
                        SELECT 1
                          FROM team_manager child_team
                         WHERE child_team.parent_team_id = tm.team_id
                           AND child_team.team_id <> tm.team_id
                    )
               )
               AND NOT EXISTS (
                    SELECT 1
                      FROM team_manager other_manager
                      JOIN employee other_pm
                        ON other_pm.employee_id = other_manager.project_manager_id
                     WHERE other_manager.team_id = tm.team_id
                       AND other_manager.project_manager_id <> g_employee_ids(i)
                       AND other_pm.hire_date <= v_check_date
                       AND (
                            other_pm.fire_date IS NULL
                            OR other_pm.fire_date >= v_check_date
                       )
               );

            IF v_gap_team_count > 0 THEN
                RAISE_APPLICATION_ERROR(
                    -20031,
                    'PM 퇴사 처리로 결재 공백이 발생합니다. 다른 재직 PM을 먼저 지정하세요. employee_id='
                    || g_employee_ids(i)
                    || ', team_count='
                    || v_gap_team_count
                );
            END IF;
        END LOOP;
    END AFTER STATEMENT;

END trg_employee_pm_fire_date_guard;
/

CREATE TABLE leave_request (
    leave_request_id      NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    employee_id           NUMBER(19) NOT NULL,
    leave_type            VARCHAR2(50 CHAR) NOT NULL,
    start_date            DATE NOT NULL,
    end_date              DATE NOT NULL,
    use_days              BINARY_FLOAT NOT NULL,
    prev_total_leave_days BINARY_FLOAT NOT NULL,
    curr_total_leave_days BINARY_FLOAT NOT NULL,
    leave_reason          VARCHAR2(200 CHAR),
    create_request_key    VARCHAR2(128 CHAR),
    create_request_hash   VARCHAR2(64 CHAR),
    status                VARCHAR2(10 CHAR) DEFAULT 'PENDING' NOT NULL,
    manager_id            NUMBER(19),
    managed_at            TIMESTAMP(6),
    managed_ip            VARCHAR2(45 CHAR),
    reject_reason         VARCHAR2(200 CHAR),
    created_at            TIMESTAMP(6) NOT NULL,
    created_ip            VARCHAR2(45 CHAR) NOT NULL,
    CONSTRAINT pk_leave_request PRIMARY KEY (leave_request_id),
    CONSTRAINT fk_leave_request_employee
        FOREIGN KEY (employee_id) REFERENCES employee(employee_id),
    CONSTRAINT fk_leave_request_manager
        FOREIGN KEY (manager_id) REFERENCES employee(employee_id),
    CONSTRAINT uk_leave_request_create_request
        UNIQUE (employee_id, create_request_key),
    CONSTRAINT ck_leave_request_create_pair CHECK (
        (create_request_key IS NULL AND create_request_hash IS NULL)
        OR
        (create_request_key IS NOT NULL AND create_request_hash IS NOT NULL)
    ),
    CONSTRAINT ck_leave_request_status CHECK (
        status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')
    )
);

CREATE TABLE basis_data (
    year   VARCHAR2(4 CHAR) NOT NULL,
    seq    NUMBER(19) NOT NULL,
    type   VARCHAR2(2 CHAR),
    data   VARCHAR2(255 CHAR),
    remark VARCHAR2(200 CHAR),
    CONSTRAINT pk_basis_data PRIMARY KEY (year, seq)
);

CREATE TABLE leave_adjustment (
    employee_id NUMBER(19) NOT NULL,
    year        VARCHAR2(4 CHAR) NOT NULL,
    sign        VARCHAR2(5 CHAR),
    leave_days  BINARY_FLOAT NOT NULL,
    reason      VARCHAR2(200 CHAR),
    created_at  TIMESTAMP(6) NOT NULL,
    created_ip  VARCHAR2(45 CHAR) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL,
    updated_ip  VARCHAR2(45 CHAR),
    CONSTRAINT pk_leave_adjustment PRIMARY KEY (employee_id, year, created_at),
    CONSTRAINT fk_leave_adjustment_employee
        FOREIGN KEY (employee_id) REFERENCES employee(employee_id)
);

CREATE TABLE holiday (
    holiday_date DATE NOT NULL,
    name         VARCHAR2(50 CHAR),
    CONSTRAINT pk_holiday PRIMARY KEY (holiday_date)
);

CREATE TABLE fcm_token (
    token_id    NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    employee_id NUMBER(19),
    fcm_token           VARCHAR2(255 CHAR) NOT NULL,
    device_os           VARCHAR2(255 CHAR),
    auth_session_marker VARCHAR2(64 CHAR),
    updated_at          TIMESTAMP(6) NOT NULL,
    updated_ip  VARCHAR2(45 CHAR),
    CONSTRAINT pk_fcm_token PRIMARY KEY (token_id),
    CONSTRAINT uk_fcm_token UNIQUE (fcm_token),
    CONSTRAINT fk_fcm_token_employee
        FOREIGN KEY (employee_id) REFERENCES employee(employee_id)
);

CREATE TABLE notification_outbox (
    outbox_id        NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    approver_ids     CLOB NOT NULL,
    title            VARCHAR2(200 CHAR) NOT NULL,
    body             VARCHAR2(1000 CHAR) NOT NULL,
    status           VARCHAR2(20 CHAR) DEFAULT 'PENDING' NOT NULL,
    attempt_count    NUMBER(10) DEFAULT 0 NOT NULL,
    next_attempt_at  TIMESTAMP(6) NOT NULL,
    claimed_at       TIMESTAMP(6),
    sent_at          TIMESTAMP(6),
    last_error       VARCHAR2(1000 CHAR),
    created_at       TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_notification_outbox PRIMARY KEY (outbox_id),
    CONSTRAINT ck_notification_outbox_status
        CHECK (status IN ('PENDING', 'PROCESSING', 'SENT', 'DEAD')),
    CONSTRAINT ck_notification_outbox_attempt
        CHECK (attempt_count >= 0)
);

CREATE TABLE password_reset_token (
    token_id     NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    employee_id  NUMBER(19) NOT NULL,
    token_hash   VARCHAR2(64 CHAR) NOT NULL,
    expires_at   TIMESTAMP(6) NOT NULL,
    consumed_at  TIMESTAMP(6),
    created_at   TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_password_reset_token PRIMARY KEY (token_id),
    CONSTRAINT uk_password_reset_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_password_reset_employee
        FOREIGN KEY (employee_id) REFERENCES employee(employee_id)
);

CREATE INDEX ix_employee_team ON employee(team_id);
CREATE INDEX ix_employee_department ON employee(department_id);
CREATE INDEX ix_team_department ON team(department_id);
CREATE INDEX ix_leave_request_employee ON leave_request(employee_id);
CREATE INDEX ix_leave_request_status_dates
    ON leave_request(status, start_date, end_date);
CREATE INDEX ix_leave_request_status_created
    ON leave_request(status, created_at, leave_request_id);
CREATE INDEX ix_leave_request_employee_created
    ON leave_request(employee_id, created_at, leave_request_id);
CREATE INDEX ix_team_manager_parent ON team_manager(parent_team_id);
CREATE INDEX ix_team_manager_project_manager ON team_manager(project_manager_id);
CREATE INDEX ix_password_reset_employee ON password_reset_token(employee_id);
CREATE INDEX ix_notification_outbox_ready
    ON notification_outbox(status, next_attempt_at, outbox_id);
