-- =====================================================================
-- annual-leave develop_v2.0
-- Oracle 21c XE canonical fresh-install schema
--
-- Fresh database: use this file after DBA creates COMMON_DATA / COMMON_INDEX.
-- This fresh-install schema includes AUTH_REFRESH_SESSION.
-- Existing develop_v1.0 database: use migration_v2_0_oracle.sql only.
-- The v1 -> v2 application migration leaves an already-existing shared
-- AUTH_REFRESH_SESSION untouched; it only migrates annual-leave application objects.
-- Oracle DDL performs implicit commits; back up an existing database first.
-- =====================================================================

WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK;

CREATE TABLE department (
    department_id   NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    department_name VARCHAR2(50 CHAR) NOT NULL,
    enabled         NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT pk_department PRIMARY KEY (department_id),
    CONSTRAINT uk_department_name UNIQUE (department_name),
    CONSTRAINT ck_department_enabled CHECK (enabled IN (0, 1))
);

COMMENT ON TABLE department IS '부서 정보';

COMMENT ON COLUMN department.department_id IS '부서 ID';
COMMENT ON COLUMN department.department_name IS '부서명';
COMMENT ON COLUMN department.enabled IS '부서 사용 여부 (1: 사용, 0: 미사용)';

CREATE TABLE team (
    team_id             NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    team_name           VARCHAR2(30 CHAR) NOT NULL,
    department_id       NUMBER(19) NOT NULL,
    enabled             NUMBER(1) DEFAULT 1 NOT NULL,
    create_request_key  VARCHAR2(128 CHAR),
    create_request_hash VARCHAR2(64 CHAR),
    CONSTRAINT pk_team PRIMARY KEY (team_id),
    CONSTRAINT uk_team_name UNIQUE (team_name),
    CONSTRAINT uk_team_create_request UNIQUE (create_request_key),
    CONSTRAINT ck_team_enabled CHECK (enabled IN (0, 1)),
    CONSTRAINT ck_team_create_request_pair CHECK (
        (create_request_key IS NULL AND create_request_hash IS NULL)
        OR
        (create_request_key IS NOT NULL AND create_request_hash IS NOT NULL)
    ),
    CONSTRAINT fk_team_department
        FOREIGN KEY (department_id) REFERENCES department(department_id)
);

COMMENT ON TABLE team IS '팀 정보';

COMMENT ON COLUMN team.team_id IS '팀 ID';
COMMENT ON COLUMN team.team_name IS '팀명';
COMMENT ON COLUMN team.department_id IS '소속 부서 ID';
COMMENT ON COLUMN team.enabled IS '팀 사용 여부 (1: 사용, 0: 미사용)';
COMMENT ON COLUMN team.create_request_key IS '팀 생성 요청 멱등성 키. 동일 요청 재시도 식별용';
COMMENT ON COLUMN team.create_request_hash IS '팀 생성 요청 payload hash. 동일 key의 요청 내용 일치 검증용';

CREATE TABLE employee (
    employee_id           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    employee_number       VARCHAR2(20 CHAR) NOT NULL,
    password              VARCHAR2(255 CHAR),
    access_count          NUMBER(10) DEFAULT 0 NOT NULL,
    accessed_ip           VARCHAR2(45 CHAR),
    accessed_at           TIMESTAMP(6),
    name                  VARCHAR2(50 CHAR) NOT NULL,
    department_id         NUMBER(19) NOT NULL,
    team_id               NUMBER(19) NOT NULL,
    position              VARCHAR2(50 CHAR),
    email                 VARCHAR2(100 CHAR),
    curr_year             VARCHAR2(4 CHAR) NOT NULL,
    curr_total_leave_days BINARY_FLOAT DEFAULT 0 NOT NULL,
    prev_year             VARCHAR2(4 CHAR),
    prev_total_leave_days BINARY_FLOAT,
    hire_date             DATE NOT NULL,
    fire_date             DATE,
    approver_id           NUMBER(19) NOT NULL,
    created_at            TIMESTAMP(6) NOT NULL,
    created_ip            VARCHAR2(45 CHAR) NOT NULL,
    updated_at            TIMESTAMP(6) NOT NULL,
    updated_ip            VARCHAR2(45 CHAR),
    CONSTRAINT pk_employee PRIMARY KEY (employee_id),
    CONSTRAINT uk_employee_number UNIQUE (employee_number),
    CONSTRAINT fk_employee_department
        FOREIGN KEY (department_id) REFERENCES department(department_id),
    CONSTRAINT fk_employee_team
        FOREIGN KEY (team_id) REFERENCES team(team_id),
    CONSTRAINT fk_employee_approver
        FOREIGN KEY (approver_id) REFERENCES employee(employee_id)
);

COMMENT ON TABLE employee IS '직원 정보';

COMMENT ON COLUMN employee.employee_id IS '직원 ID';
COMMENT ON COLUMN employee.employee_number IS '사번';
COMMENT ON COLUMN employee.password IS 'BCrypt 비밀번호 hash. NULL이면 사용 등록 전 상태';
COMMENT ON COLUMN employee.access_count IS '연속 로그인 실패 횟수';
COMMENT ON COLUMN employee.accessed_ip IS '최근 인증 접근 IP 주소';
COMMENT ON COLUMN employee.accessed_at IS '최근 인증 접근 시각';
COMMENT ON COLUMN employee.name IS '직원명';
COMMENT ON COLUMN employee.department_id IS '소속 부서 ID';
COMMENT ON COLUMN employee.team_id IS '소속 팀 ID';
COMMENT ON COLUMN employee.position IS '직급';
COMMENT ON COLUMN employee.email IS '이메일 주소';
COMMENT ON COLUMN employee.curr_year IS '현재 연차 기준연도';
COMMENT ON COLUMN employee.curr_total_leave_days IS '현재 기준연도의 총 연차일수';
COMMENT ON COLUMN employee.prev_year IS '이전 연차 기준연도';
COMMENT ON COLUMN employee.prev_total_leave_days IS '이전 기준연도의 총 연차일수';
COMMENT ON COLUMN employee.hire_date IS '입사일';
COMMENT ON COLUMN employee.fire_date IS '퇴사일 (NULL이면 재직)';
COMMENT ON COLUMN employee.approver_id IS '기본 결재자 직원 ID';
COMMENT ON COLUMN employee.created_at IS '생성 시각';
COMMENT ON COLUMN employee.created_ip IS '생성 요청 IP 주소';
COMMENT ON COLUMN employee.updated_at IS '수정 시각';
COMMENT ON COLUMN employee.updated_ip IS '수정 요청 IP 주소';

-- =====================================================================
-- 공통 SSO Refresh Token Rotation session
--
-- 연차/자산관리가 같은 refresh family/session row를 사용한다.
-- COMMON_DATA / COMMON_INDEX는 sql/dba_prepare_common_auth_tablespace.sql로 DBA가 먼저 준비한다.
-- =====================================================================
CREATE TABLE auth_refresh_session (
    session_id                VARCHAR2(36)      NOT NULL,
    employee_id               NUMBER(19)        NOT NULL,
    token_hash                VARCHAR2(64)      NOT NULL,
    previous_token_hash       VARCHAR2(64),
    previous_valid_until      TIMESTAMP(6),
    created_at                TIMESTAMP(6)      NOT NULL,
    last_rotated_at           TIMESTAMP(6)      NOT NULL,
    idle_expires_at           TIMESTAMP(6)      NOT NULL,
    absolute_expires_at       TIMESTAMP(6)      NOT NULL,
    revoked_at                TIMESTAMP(6),
    revoked_reason            VARCHAR2(40),
    rotation_count            NUMBER(10) DEFAULT 0 NOT NULL,
    CONSTRAINT pk_auth_refresh_session
        PRIMARY KEY (session_id) USING INDEX TABLESPACE COMMON_INDEX,
    CONSTRAINT fk_ars_employee
        FOREIGN KEY (employee_id) REFERENCES employee(employee_id),
    CONSTRAINT ck_ars_rotation_count CHECK (rotation_count >= 0),
    CONSTRAINT ck_ars_expiry_order CHECK (idle_expires_at <= absolute_expires_at)
)
TABLESPACE COMMON_DATA;

COMMENT ON TABLE auth_refresh_session IS '공통 인증 Refresh Token Rotation 세션. 원문 token은 저장하지 않는다.';

COMMENT ON COLUMN auth_refresh_session.session_id IS 'Refresh family/session UUID';
COMMENT ON COLUMN auth_refresh_session.employee_id IS '세션 소유 직원 ID';
COMMENT ON COLUMN auth_refresh_session.token_hash IS '현재 opaque refresh token SHA-256(Base64URL) hash';
COMMENT ON COLUMN auth_refresh_session.previous_token_hash IS '직전 token hash. 짧은 동시 refresh grace 판별용';
COMMENT ON COLUMN auth_refresh_session.previous_valid_until IS '직전 token을 동시 rotation으로 간주할 수 있는 grace 종료시각';
COMMENT ON COLUMN auth_refresh_session.created_at IS '세션 최초 생성 시각';
COMMENT ON COLUMN auth_refresh_session.last_rotated_at IS '마지막 refresh token rotation 시각';
COMMENT ON COLUMN auth_refresh_session.idle_expires_at IS '유휴 만료 시각. rotation 시 정책 범위에서 갱신된다.';
COMMENT ON COLUMN auth_refresh_session.absolute_expires_at IS '최초 로그인 기준 절대 만료. rotation으로 연장하지 않는다.';
COMMENT ON COLUMN auth_refresh_session.revoked_at IS '세션 폐기 시각';
COMMENT ON COLUMN auth_refresh_session.revoked_reason IS '세션 폐기 사유';
COMMENT ON COLUMN auth_refresh_session.rotation_count IS 'Refresh token rotation 횟수';

CREATE INDEX ix_ars_employee
    ON auth_refresh_session(employee_id)
    TABLESPACE COMMON_INDEX;

CREATE INDEX ix_ars_expiry
    ON auth_refresh_session(absolute_expires_at, idle_expires_at)
    TABLESPACE COMMON_INDEX;


CREATE TABLE team_manager (
    team_id            NUMBER(19) NOT NULL,
    project_manager_id NUMBER(19) NOT NULL,
    parent_team_id     NUMBER(19) NOT NULL,
    CONSTRAINT pk_team_manager PRIMARY KEY (team_id, project_manager_id),
    CONSTRAINT fk_team_manager_team
        FOREIGN KEY (team_id) REFERENCES team(team_id),
    CONSTRAINT fk_team_manager_project_manager
        FOREIGN KEY (project_manager_id) REFERENCES employee(employee_id),
    CONSTRAINT fk_team_manager_parent_team
        FOREIGN KEY (parent_team_id) REFERENCES team(team_id)
);

COMMENT ON TABLE team_manager IS '팀별 프로젝트 관리자와 상위 팀 관계';

COMMENT ON COLUMN team_manager.team_id IS '관리 대상 팀 ID';
COMMENT ON COLUMN team_manager.project_manager_id IS '프로젝트 관리자 직원 ID';
COMMENT ON COLUMN team_manager.parent_team_id IS '상위 팀 ID';

-- =====================================================================
-- DB-level guard: PM 퇴사일 직접 UPDATE로 결재 공백이 생기는 것을 차단한다.
--
-- Row trigger에서 EMPLOYEE를 다시 조회하면 ORA-04091(mutating table)이 발생할 수
-- 있으므로 compound trigger의 AFTER STATEMENT 단계에서 최종 상태를 검증한다.
-- 한 UPDATE문에서 여러 PM의 FIRE_DATE를 동시에 바꾸는 경우도 최종 상태 기준으로
-- 함께 검증된다.
-- =====================================================================
CREATE OR REPLACE TRIGGER trg_employee_pm_fire_date_guard
FOR UPDATE OF fire_date ON employee
COMPOUND TRIGGER

    TYPE t_employee_id_list IS TABLE OF NUMBER(19) INDEX BY PLS_INTEGER;
    g_employee_ids t_employee_id_list;
    g_employee_count PLS_INTEGER := 0;

    AFTER EACH ROW IS
    BEGIN
        -- 퇴사일 제거(NULL)는 재활성화 방향이므로 차단 대상이 아니다.
        IF :NEW.fire_date IS NOT NULL
           AND (:OLD.fire_date IS NULL OR :OLD.fire_date <> :NEW.fire_date) THEN
            g_employee_count := g_employee_count + 1;
            g_employee_ids(g_employee_count) := :NEW.employee_id;
        END IF;
    END AFTER EACH ROW;

    AFTER STATEMENT IS
        v_fire_date      DATE;
        v_inactive_from  DATE;
        v_check_date     DATE;
        v_gap_team_count NUMBER;
    BEGIN
        FOR i IN 1 .. g_employee_count LOOP
            SELECT fire_date
              INTO v_fire_date
              FROM employee
             WHERE employee_id = g_employee_ids(i);

            IF v_fire_date IS NULL THEN
                CONTINUE;
            END IF;

            -- LocalDate.MAX(9999-12-31)는 +1 시 Oracle DATE 범위를 벗어날 수 있다.
            IF v_fire_date >= DATE '9999-12-31' THEN
                v_inactive_from := v_fire_date;
            ELSE
                v_inactive_from := v_fire_date + 1;
            END IF;

            -- 과거 일자로 소급 퇴사 처리하더라도 현재 조직에 결재 공백이 생기면 막는다.
            v_check_date := GREATEST(v_inactive_from, TRUNC(SYSDATE));

            SELECT COUNT(DISTINCT tm.team_id)
              INTO v_gap_team_count
              FROM team_manager tm
             WHERE tm.project_manager_id = g_employee_ids(i)
               AND (
                    EXISTS (
                        SELECT 1
                          FROM employee dependent_employee
                         WHERE dependent_employee.team_id = tm.team_id
                           AND dependent_employee.employee_id <> g_employee_ids(i)
                           AND dependent_employee.hire_date <= v_check_date
                           AND (
                                dependent_employee.fire_date IS NULL
                                OR dependent_employee.fire_date >= v_check_date
                           )
                    )
                    OR EXISTS (
                        SELECT 1
                          FROM team_manager child_team
                         WHERE child_team.parent_team_id = tm.team_id
                           AND child_team.team_id <> tm.team_id
                    )
               )
               AND NOT EXISTS (
                    SELECT 1
                      FROM team_manager other_manager
                      JOIN employee other_pm
                        ON other_pm.employee_id = other_manager.project_manager_id
                     WHERE other_manager.team_id = tm.team_id
                       AND other_manager.project_manager_id <> g_employee_ids(i)
                       AND other_pm.hire_date <= v_check_date
                       AND (
                            other_pm.fire_date IS NULL
                            OR other_pm.fire_date >= v_check_date
                       )
               );

            IF v_gap_team_count > 0 THEN
                RAISE_APPLICATION_ERROR(
                    -20031,
                    'PM 퇴사 처리로 결재 공백이 발생합니다. 다른 재직 PM을 먼저 지정하세요. employee_id='
                    || g_employee_ids(i)
                    || ', team_count='
                    || v_gap_team_count
                );
            END IF;
        END LOOP;
    END AFTER STATEMENT;

END trg_employee_pm_fire_date_guard;
/

CREATE TABLE leave_request (
    leave_request_id      NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    employee_id           NUMBER(19) NOT NULL,
    leave_type            VARCHAR2(50 CHAR) NOT NULL,
    start_date            DATE NOT NULL,
    end_date              DATE NOT NULL,
    use_days              BINARY_FLOAT NOT NULL,
    prev_total_leave_days BINARY_FLOAT NOT NULL,
    curr_total_leave_days BINARY_FLOAT NOT NULL,
    leave_reason          VARCHAR2(200 CHAR),
    create_request_key    VARCHAR2(128 CHAR),
    create_request_hash   VARCHAR2(64 CHAR),
    status                VARCHAR2(10 CHAR) DEFAULT 'PENDING' NOT NULL,
    manager_id            NUMBER(19),
    managed_at            TIMESTAMP(6),
    managed_ip            VARCHAR2(45 CHAR),
    reject_reason         VARCHAR2(200 CHAR),
    created_at            TIMESTAMP(6) NOT NULL,
    created_ip            VARCHAR2(45 CHAR) NOT NULL,
    CONSTRAINT pk_leave_request PRIMARY KEY (leave_request_id),
    CONSTRAINT fk_leave_request_employee
        FOREIGN KEY (employee_id) REFERENCES employee(employee_id),
    CONSTRAINT fk_leave_request_manager
        FOREIGN KEY (manager_id) REFERENCES employee(employee_id),
    CONSTRAINT uk_leave_request_create_request
        UNIQUE (employee_id, create_request_key),
    CONSTRAINT ck_leave_request_create_pair CHECK (
        (create_request_key IS NULL AND create_request_hash IS NULL)
        OR
        (create_request_key IS NOT NULL AND create_request_hash IS NOT NULL)
    ),
    CONSTRAINT ck_leave_request_status CHECK (
        status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')
    )
);

COMMENT ON TABLE leave_request IS '휴가 신청 정보';

COMMENT ON COLUMN leave_request.leave_request_id IS '휴가 신청 ID';
COMMENT ON COLUMN leave_request.employee_id IS '신청 직원 ID';
COMMENT ON COLUMN leave_request.leave_type IS '휴가 유형 (FULL: 연차, AM_HALF: 오전 반차, PM_HALF: 오후 반차, ALTERNATIVE: 대체 휴가, PARENTAL: 출산 휴가, FAMILY: 가족 돌봄 휴가, OTHER: 기타)';
COMMENT ON COLUMN leave_request.start_date IS '휴가 시작일';
COMMENT ON COLUMN leave_request.end_date IS '휴가 종료일';
COMMENT ON COLUMN leave_request.use_days IS '사용 연차 일수';
COMMENT ON COLUMN leave_request.prev_total_leave_days IS '신청 시점 이전 기준연도의 총 연차일수 snapshot';
COMMENT ON COLUMN leave_request.curr_total_leave_days IS '신청 시점 현재 기준연도의 총 연차일수 snapshot';
COMMENT ON COLUMN leave_request.leave_reason IS '휴가 신청 사유. 연차/반차 외 휴가 유형은 필수';
COMMENT ON COLUMN leave_request.create_request_key IS '휴가 신청 멱등성 키. 동일 요청 재시도 식별용';
COMMENT ON COLUMN leave_request.create_request_hash IS '휴가 신청 payload hash. 동일 key의 요청 내용 일치 검증용';
COMMENT ON COLUMN leave_request.status IS '처리 상태 (PENDING: 승인 대기, APPROVED: 승인 완료, REJECTED: 반려, CANCELLED: 사용자 취소)';
COMMENT ON COLUMN leave_request.manager_id IS '승인 또는 반려를 처리한 관리자 직원 ID';
COMMENT ON COLUMN leave_request.managed_at IS '승인 또는 반려 처리 시각';
COMMENT ON COLUMN leave_request.managed_ip IS '승인 또는 반려 처리 요청 IP 주소';
COMMENT ON COLUMN leave_request.reject_reason IS '반려 사유';
COMMENT ON COLUMN leave_request.created_at IS '생성 시각';
COMMENT ON COLUMN leave_request.created_ip IS '생성 요청 IP 주소';

CREATE TABLE basis_data (
    year   VARCHAR2(4 CHAR) NOT NULL,
    seq    NUMBER(19) NOT NULL,
    type   VARCHAR2(2 CHAR),
    data   VARCHAR2(255 CHAR),
    remark VARCHAR2(200 CHAR),
    CONSTRAINT pk_basis_data PRIMARY KEY (year, seq)
);

COMMENT ON TABLE basis_data IS '연도별 연차 및 인증 기준정보';

COMMENT ON COLUMN basis_data.year IS '기준 연도';
COMMENT ON COLUMN basis_data.seq IS '기준정보 코드 (BasisDataType code)';
COMMENT ON COLUMN basis_data.type IS '데이터 파싱 타입 (0: BOOLEAN, 1: INTEGER, 2: LONG, 3: FLOAT, 4: DOUBLE, 5: STRING)';
COMMENT ON COLUMN basis_data.data IS '기준정보 값';
COMMENT ON COLUMN basis_data.remark IS '비고 (선택)';

CREATE TABLE leave_adjustment (
    employee_id NUMBER(19) NOT NULL,
    year        VARCHAR2(4 CHAR) NOT NULL,
    sign        VARCHAR2(5 CHAR),
    leave_days  BINARY_FLOAT NOT NULL,
    reason      VARCHAR2(200 CHAR),
    created_at  TIMESTAMP(6) NOT NULL,
    created_ip  VARCHAR2(45 CHAR) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL,
    updated_ip  VARCHAR2(45 CHAR),
    CONSTRAINT pk_leave_adjustment PRIMARY KEY (employee_id, year, created_at),
    CONSTRAINT fk_leave_adjustment_employee
        FOREIGN KEY (employee_id) REFERENCES employee(employee_id)
);

COMMENT ON TABLE leave_adjustment IS '직원별 연차 조정 이력';

COMMENT ON COLUMN leave_adjustment.employee_id IS '연차 조정 대상 직원 ID';
COMMENT ON COLUMN leave_adjustment.year IS '연차 조정 기준연도';
COMMENT ON COLUMN leave_adjustment.sign IS '조정 부호 (plus: 가산, minus: 차감)';
COMMENT ON COLUMN leave_adjustment.leave_days IS '조정 연차 일수';
COMMENT ON COLUMN leave_adjustment.reason IS '연차 조정 사유';
COMMENT ON COLUMN leave_adjustment.created_at IS '생성 시각';
COMMENT ON COLUMN leave_adjustment.created_ip IS '생성 요청 IP 주소';
COMMENT ON COLUMN leave_adjustment.updated_at IS '수정 시각';
COMMENT ON COLUMN leave_adjustment.updated_ip IS '수정 요청 IP 주소';

CREATE TABLE holiday (
    holiday_date DATE NOT NULL,
    name         VARCHAR2(50 CHAR),
    CONSTRAINT pk_holiday PRIMARY KEY (holiday_date)
);

COMMENT ON TABLE holiday IS '공휴일 정보';

COMMENT ON COLUMN holiday.holiday_date IS '공휴일 날짜';
COMMENT ON COLUMN holiday.name IS '공휴일명';

CREATE TABLE fcm_token (
    token_id    NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    employee_id NUMBER(19),
    fcm_token           VARCHAR2(255 CHAR) NOT NULL,
    device_os           VARCHAR2(255 CHAR),
    auth_session_marker VARCHAR2(64 CHAR),
    updated_at          TIMESTAMP(6) NOT NULL,
    updated_ip  VARCHAR2(45 CHAR),
    CONSTRAINT pk_fcm_token PRIMARY KEY (token_id),
    CONSTRAINT uk_fcm_token UNIQUE (fcm_token),
    CONSTRAINT fk_fcm_token_employee
        FOREIGN KEY (employee_id) REFERENCES employee(employee_id)
);

COMMENT ON TABLE fcm_token IS 'FCM 푸시 알림 기기 token';

COMMENT ON COLUMN fcm_token.token_id IS 'FCM token 행 ID';
COMMENT ON COLUMN fcm_token.employee_id IS '현재 token 소유 직원 ID';
COMMENT ON COLUMN fcm_token.fcm_token IS 'Firebase Cloud Messaging 기기 token. 기기별 유일';
COMMENT ON COLUMN fcm_token.device_os IS '기기 운영체제';
COMMENT ON COLUMN fcm_token.auth_session_marker IS '마지막으로 동기화한 Web SSO refresh session marker. native/legacy client는 NULL';
COMMENT ON COLUMN fcm_token.updated_at IS '수정 시각';
COMMENT ON COLUMN fcm_token.updated_ip IS '수정 요청 IP 주소';

CREATE TABLE password_reset_token (
    token_id     NUMBER(19) GENERATED BY DEFAULT AS IDENTITY,
    employee_id  NUMBER(19) NOT NULL,
    token_hash   VARCHAR2(64 CHAR) NOT NULL,
    expires_at   TIMESTAMP(6) NOT NULL,
    consumed_at  TIMESTAMP(6),
    created_at   TIMESTAMP(6) NOT NULL,
    CONSTRAINT pk_password_reset_token PRIMARY KEY (token_id),
    CONSTRAINT uk_password_reset_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_password_reset_employee
        FOREIGN KEY (employee_id) REFERENCES employee(employee_id)
);

COMMENT ON TABLE password_reset_token IS '비밀번호 재설정 일회용 token';

COMMENT ON COLUMN password_reset_token.token_id IS '비밀번호 재설정 token ID';
COMMENT ON COLUMN password_reset_token.employee_id IS '비밀번호 재설정 대상 직원 ID';
COMMENT ON COLUMN password_reset_token.token_hash IS '원문 비밀번호 재설정 token의 SHA-256 hash';
COMMENT ON COLUMN password_reset_token.expires_at IS 'token 만료 시각';
COMMENT ON COLUMN password_reset_token.consumed_at IS 'token 사용 완료 시각';
COMMENT ON COLUMN password_reset_token.created_at IS '생성 시각';

CREATE INDEX ix_employee_team ON employee(team_id);
CREATE INDEX ix_employee_department ON employee(department_id);
CREATE INDEX ix_team_department ON team(department_id);
CREATE INDEX ix_leave_request_employee ON leave_request(employee_id);
CREATE INDEX ix_leave_request_status_dates
    ON leave_request(status, start_date, end_date);
CREATE INDEX ix_leave_request_status_created
    ON leave_request(status, created_at, leave_request_id);
CREATE INDEX ix_leave_request_employee_created
    ON leave_request(employee_id, created_at, leave_request_id);
CREATE INDEX ix_team_manager_parent ON team_manager(parent_team_id);
CREATE INDEX ix_team_manager_project_manager ON team_manager(project_manager_id);
CREATE INDEX ix_password_reset_employee ON password_reset_token(employee_id);
